device: cuda
train_parameters:
  max_epochs: 20
  batch_size: 64
  freq_of_test: 2
  learning_rate: 1e-2
  lr_scheduler_step_size: 4
  lr_decay: 0.3333
  per_series_lr_multip: 0.5
  gradient_clipping_threshold: 50
  rnn_weight_decay: 0
  noise_std: 0.0001
  level_variability_penalty: 100
  percentile: 50
  training_percentile: 65
  ensemble: False
data_parameters:
  max_periods: 15
  seasonality: [7]
  input_size: 7
  output_size: 14
model_parameters:
  n_models: 5
  n_top: 4
  cell_type: 'LSTM'
  state_hsize: 40
  dilations: [[1, 7, 28]]
  add_nl_layer: True
  random_seed: 1
