device: cuda
train_parameters:
  max_epochs: 20
  batch_size: 32
  freq_of_test: 5
  learning_rate: 1e-2
  lr_scheduler_step_size: 7
  lr_decay: 0.5
  per_series_lr_multip: 1.0
  gradient_clipping_threshold: 50
  rnn_weight_decay: 0
  noise_std: 0.001
  level_variability_penalty: 30
  percentile: 50
  training_percentile: 50
  ensemble: True
data_parameters:
  max_periods: 371
  seasonality: [24, 168]
  input_size: 24
  output_size: 48
model_parameters:
  cell_type: 'LSTM'
  state_hsize: 40
  dilations: [[1, 4, 24, 168]]
  add_nl_layer: FALSE
  random_seed: 1
