device: cuda
train_parameters:
  max_epochs: 15
  batch_size: 64
  freq_of_test: 4
  learning_rate: 7e-4
  lr_scheduler_step_size: 12
  lr_decay: 0.2
  per_series_lr_multip: 0.5
  gradient_clipping_threshold: 20
  rnn_weight_decay: 0
  noise_std: 0.001
  level_variability_penalty: 50
  testing_percentile: 50
  training_percentile: 45
  ensemble: False
data_parameters:
  max_periods: 36
  seasonality: [12]
  input_size: 12
  output_size: 18
  frequency: 'M'
model_parameters:
  cell_type: 'LSTM'
  state_hsize: 50
  dilations: [[1, 3, 6, 12]]
  add_nl_layer: FALSE
  random_seed: 1
