device: cuda
train_parameters:
  max_epochs: 50
  batch_size: 32
  freq_of_test: 10
  learning_rate: 1e-2
  lr_scheduler_step_size: 10
  lr_decay: 0.5
  per_series_lr_multip: 1.0
  gradient_clipping_threshold: 20
  rnn_weight_decay: 0
  noise_std: 0.001
  level_variability_penalty: 100
  testing_percentile: 50
  training_percentile: 50
  ensemble: True
data_parameters:
  max_periods: 31
  seasonality: []
  input_size: 10
  output_size: 13
model_parameters:
  cell_type: 'ResLSTM'
  state_hsize: 40
  dilations: [[1, 52]]
  add_nl_layer: False
  random_seed: 2
  frequency: 'W'
