device: cpu
train_parameters:
  max_epochs: 25
  batch_size: 4
  freq_of_test: 5
  learning_rate: 1e-4
  lr_scheduler_step_size: 10
  lr_decay: 0.1
  per_series_lr_multip: 0.8
  gradient_clipping_threshold: 50
  rnn_weight_decay: 0
  noise_std: 0.001
  level_variability_penalty: 100
  testing_percentile: 50
  training_percentile: 50
  ensemble: False
data_parameters:
  max_periods: 25
  seasonality: []
  input_size: 4
  output_size: 6
model_parameters:
  cell_type: 'LSTM'
  state_hsize: 40
  dilations: [[1], [6]]
  add_nl_layer: FALSE
  random_seed: 117982
  frequency: 'Y'
